### ISSUE TITLE
λ-calculus with alligators

### ISSUE THREAD

**Issue by lbeziaud** [InfoSansOrdi/pedago-rennes#23]
Hello,

I stumbled upon [Alligator Eggs!](http://worrydream.com/AlligatorEggs/). It is a puzzle game with coloured alligators and eggs. The game represents the untyped lambda calculus (see the bottom of the web page). It could be a nice resource if someone is searching for an idea to try and adapt. I asked the author about the licence: it "is in the public domain, and you can do anything you like with it."

![example](http://worrydream.com/AlligatorEggs/eating_2.png)

**Comment by mquinson** [comment]
Bonjour Louis,

pourrais-tu faire une PR pour ajouter ce lien à la page pedago1?

Merci, Mt.
